### ISSUE TITLE
Not working on matlab-mode

### ISSUE THREAD

**Issue by Nidish96** [emacs-tree-sitter/ts-fold#109]
The code folding doesn't work while on matlab-mode. 

Any tips on how to debug this?

**Comment by jcs090218** [comment]
There is no `matlab` folding, see https://github.com/emacs-tree-sitter/ts-fold/blob/07da6590aaf0b121dff97fe4bc12fa6486fadcde/ts-fold.el#L61.

Therefore, this is a feature request! 🤔

**Comment by Nidish96** [comment]
I've done just this and created a pull request here: https://github.com/emacs-tree-sitter/ts-fold/pull/110
