### ISSUE TITLE
Move to emacs tree-sitter org?

### ISSUE THREAD

**Issue by jcs090218** [emacs-tree-sitter/ts-fold#30]
Hi @ubolonton,

I am pinging you here to ask weather you would like me to move this package to `emacs-tree-sitter` so it could live under the same domain? I saw [Spacemacs]() and [Doom Emacs]() have added `tree-sitter` support, along with this package. I think it would be great so it doesn't live under my name `jcs090218` when defining a recipe. And could be much organized (somehow)?

**Short version:** Do you think this package should live under `emacs-tree-sitter` org? LMKWYT?

**Comment by ubolonton** [comment]
Yes, I think this makes sense. 
I currently don't have bandwidth for digital life's tasks though.
What logistics do you need me to do? Org/repo membership?

cc @meain who has been helping me with some `tree-sitter-langs` maintenance.

**Comment by jcs090218** [comment]
Awesome! I think the org membership should be good; it will be more convenient for me. Just make sure I have the correct access to this repo, and... the repo transferring permission (allow me to transfer this repo to the org)?

**Comment by ubolonton** [comment]
> I think the org membership should be good;

Done.

**Comment by jcs090218** [comment]
Nice! Let me move this repo to the org! ;)

**Comment by jcs090218** [comment]
Great! It works! :) I think this issue can be closed now! Thank you!
