### ISSUE TITLE
Feature request: Simplifying the process of adding new fold parsing definitions

### ISSUE THREAD

**Issue by samrjack** [emacs-tree-sitter/ts-fold#35]
Hello, I've recently started using ts-fold and have really loved being able to define my own set of folds for languages I use quite often. One issue I've had with it though is how difficult it is to add my own definitions to the existing alist without defining the variable myself or modifying the package's source code. The main cause for pain is the use of the `ts-fold-foldable-node-alist` variable which has to get updated every time the `ts-fold-range-alist` variable gets updated. To that end I'm currently using the following function as a hack to update both variables for a major mode:

```emacs-lisp
  (defun local/update-ts-fold-definitions (mode rules)
    "Update the provided MODE with the new set of folding RULES.
MODE should be a programming mode such as go-mode.
RULES should be a list of folding rules in the format of (ts-element . folding-function)"
    (setf (alist-get mode ts-fold-range-alist) rules)
    (setq ts-fold-foldable-node-alist
          (let (alist)
            (dolist (item ts-fold-range-alist)
              (let ((mode (car item))
                    nodes)
                (dolist (rule (cdr item))
                  (push (car rule) nodes))
                (push (cons mode nodes) alist)))
            alist)))
```

It works fine for now but I think it would be cleaner if ts-fold itself had a function for updating the fold definition alist variables. That way, it would be easier for people to only define the minimal information needed within their own configs for adding new folds as well as making code a lot easier to share.

Also, from a design perspective, I'm wondering about the necessity of duplicating the node information within `ts-fold-foldable-node-alist`. Was it for performance gains or some other reason? Just trying to get better at elisp myself so I'd appreciate the insight!

**Comment by samrjack** [comment]
Ya, that piece of code is where I pulled my snippet of code from above. The problem I was running into is that `:set` in `defcustom` only updates when a user uses the customize user interface but not when they change the value through other means. Since I want to be able to set these values in my config, is there a way to set them cleanly while triggering the set lambda?

**Comment by jcs090218** [comment]
There isn't a way to do this, unfortunately. I think it's a good time to refactor some of these code, feel free to share your thought or make PR if you like. :)

**Comment by samrjack** [comment]
Will try to take a look this weekend!

**Comment by samrjack** [comment]
Opened the above PR with the changes I made. I've been using these changes in my own emacs for a couple of days now and haven't run into issues. That said, if you have time, pull it down and give it a try yourself. If this gets accepted and pulled in, I'll also update the README so that it has more info about updating the folding definitions.

**Comment by jcs090218** [comment]
> If this gets accepted and pulled in, I'll also update the README so that it has more info about updating the folding definitions.

Oh, didn't realize this comment before I merged the PR. Yes, please do update the README! Thank you for your contribution! 😄
