### ISSUE TITLE
[feature request] ability to disable comment folding

### ISSUE THREAD

**Issue by pedro-nonfree** [emacs-tree-sitter/ts-fold#44]
I really like the function folding it does this package; but I would like to avoid multiline comment folding?

```sh
main() {
  # example 1
  echo 'hi'
  # example 2
  echo 'hi'
  # example 3
  # example 4
  # example 5
  echo 'hi'
  # example 3
  # example 4
  # example 5
  echo 'hi'
  echo 'hi'
  echo 'hi'
  # example 3
  # example 5
  echo 'hi'
}

main "${@}"
```

given the following example I see a lot of mess in the indicator part (and also, makes it more complex to do the folding that you really want, in my case: function folding):

![image](https://user-images.githubusercontent.com/39959198/210172971-878bb335-48b9-49c9-b981-b4b9c2fbee73.png)

and I would like something more basic, like having comments that don't make additional foldings:

![image](https://user-images.githubusercontent.com/39959198/210172991-5c363c86-1eaf-417b-8e50-057de9e72cb7.png)

**Comment by jcs090218** [comment]
You can now disable it with `ts-fold-line-comment-mode`, default is disabled!

Happy New Year! 🥳

**Comment by pedro-nonfree** [comment]
oh waw, what a sweet surprise @jcs090218 !! thank you!

To upgrade I did

```sh
cd ~/.emacs.d/straight/repos/ts-fold
git pull
```

and then, I evaluated the emacs lisp expression to rebuild it:

```lisp
(use-package ts-fold
  :straight (ts-fold :type git :host github :repo "emacs-tree-sitter/ts-fold"))
```

and then I restarted emacs, and looks like now by default it does not suggest comment folding, a decision that I support

so this is a screen capture just configuring it this way

```lisp
;; src https://github.com/emacs-tree-sitter/ts-fold
(use-package ts-fold
  :straight (ts-fold :type git :host github :repo "emacs-tree-sitter/ts-fold"))
;; Else, a hook can be added to tree-sitter directly.
(add-hook 'tree-sitter-after-on-hook #'ts-fold-indicators-mode)
(global-set-key (kbd "C-c f") 'ts-fold-toggle)
```

![image](https://user-images.githubusercontent.com/39959198/210182525-22aed0cb-7d4c-479f-8a5d-5876d51ff73a.png)
