### ISSUE TITLE
Line-Reminder compatibility doesn't work

### ISSUE THREAD

**Issue by chookity-pokk** [emacs-tree-sitter/ts-fold#49]
I used the snippet from the README to try and get this to work with line-reminder, but anytime I try to save or edit the file I get the below error in my minibuffer. It seems line line-reminder doesn't have the `line-reminder--change-lines` or `line-reminder--saved-lines` calls anymore. I think they were replaced with `line-reminder--line-status`, but I don't know enough elisp to be certain.

```
cond: Symbol’s value as variable is void: line-reminder--change-lines
```

**Comment by jcs090218** [comment]
The README is deprecated. Sorry about that, you can see my config

https://github.com/jcs-emacs/jcs-emacs/blob/4e168a5d90d4062304e96de47da46bc597268c80/modules/editor/fold/config.el

**Comment by chookity-pokk** [comment]
Grabbing the `jcs-advice-add` function makes that work when a line is edited, but not saved. Once a line is saved though it goes back to the grey default color instead of green. This is what I grabbed from your setup.

```

(defmacro jcs-advice-add (symbols where &rest body)
  "Global advice-add utility."
  (declare (indent 2))
  `(cond ((listp ,symbols)
          (dolist (symbol ,symbols)
            (advice-add symbol ,where (lambda (&optional arg0 &rest args) ,@body))))
         (t (advice-add ,symbols ,where (lambda (&optional arg0 &rest args) ,@body)))))

(use-package ts-fold
  :hook (tree-sitter-after-on . ts-fold-line-comment-mode)
  :hook (tree-sitter-after-on . ts-fold-indicators-mode)
  :init
  (setq ts-fold-indicators-fringe 'left-fringe
        ts-fold-indicators-face-function
        (lambda (pos &rest _)
          ;; Return the face of it's function.
          (line-reminder--get-face (line-number-at-pos pos t))))
  :config
  (require 'line-reminder)
  (jcs-advice-add 'line-reminder-transfer-to-saved-lines :after
    ;; Refresh indicators for package `ts-fold'.
    (ts-fold-indicators-refresh)))
```

I played around with it a bit but couldn't get the green to show up. Unless that's the expected behavior?

**Comment by jcs090218** [comment]
What it does is to apply face nicely.

![Image 1](https://user-images.githubusercontent.com/8685505/216792868-58b5990a-9b5b-45ea-9992-d296032848b1.png)

If you are getting behavior like this, then it's expected.

**Comment by chookity-pokk** [comment]
Okay, turns out to be a theme issue on my end. It does appear to be working correctly. I'll open a PR with an edited README.

**Comment by jcs090218** [comment]
The issue can be closed now? Thanks for the changes and the issue report!

**Comment by chookity-pokk** [comment]
Yep! Thank you for the fast response and the help!
