### ISSUE TITLE
Folding by custom sexp query

### ISSUE THREAD

**Issue by tlkahn** [emacs-tree-sitter/ts-fold#54]
I'm considering adding a feature that allows custom folding through a tree-sitter sexp query (validated by the `tree-siter-query-builder`). With some initial attempts, I couldn't get it working. Would anyone be able to take a look and see if it's possible to implement this feature? (or at least let me know what goes wrong with my approach?)

## My steps:

- Appending custom queries by `vconcat` with `range-patterns`. Please see my code [here](https://github.com/tlkahn/ts-fold/commit/d1305ef01301ba1ad0b14f18a2ac4843307ee627)
- In Emacs init file, you add the following snippets:
```elisp
(setq ts-fold-pattern-alist
      '((python-mode . (((argument_list) @name (\#match? @name "\"[^\\n]*\\n+[^\\n]*\""))))))
```
- Update the `tsc--stringify-patterns` function of [tsc.el](https://github.com/emacs-tree-sitter/elisp-tree-sitter/blob/master/core/tsc.el#L223) to:
```elisp
(defun tsc--stringify-patterns (patterns)
  "Convert PATTERNS into a query string that can be passed to `tsc--make-query'."
  (cond
   ((stringp patterns) patterns)
   ((sequencep patterns)
    ;; XXX: This is hacky.
    (thread-last (mapconcat (lambda (p) (format "%S" p)) patterns "\n")
      (replace-regexp-in-string (regexp-quote "\\?") "?")
      (replace-regexp-in-string (regexp-quote "\\.") ".")
      (replace-regexp-in-string (regexp-quote "\\n") "\n")
      (replace-regexp-in-string (regexp-quote "\\#") "#")))
   (t (error "Invalid patterns"))))
```

## Outcome:

- Parsing seems to work. If I add `(message (format patterns))` before this (line)[https://github.com/emacs-tree-sitter/elisp-tree-sitter/blob/master/core/tsc.el#L242], I will get `[(function_definition) @name (class_definition) @name (list) @name (dictionary) @name (comment) @name ((argument_list) @name (#match? @name "[^\n]*\n+[^\n]*")) @name]`
- But I got this error: `Error: (tsc-query-invalid-node-type "" (11 . 1) 103)`. It seems tsc is returning invalid nodes, which confused me. The sexp query above works well with `tree-siter-query-builder`.

Any thoughts?

**Comment by jcs090218** [comment]
Normally the sexp tokens are hidden in the builder. If I am implementing this feature, I might use these functions to help me get the tokens I need, and avoid regexp as much as possible (depends on what you want to do).

- `ts-fold-get-children`
- `ts-fold-get-children-traverse`
- `ts-fold-find-children`
- `ts-fold-find-children-traverse`
- `ts-fold-find-parent`
- `tsc-get-next-sibling`
- `tsc-get-prev-sibling`

Once you found the token you need, then just return the fold range using that token. See our documentation https://github.com/emacs-tree-sitter/ts-fold#-writing-new-fold-functions.

Why avoid regex? What is hidden tokens? Read the code review thread https://github.com/emacs-tree-sitter/ts-fold/pull/42#discussion_r1058050749.

**Comment by tlkahn** [comment]
Thanks a lot for the explanation! This is extremely helpful. I will rely on AST walk-through as much as possible.

So here is my use case. I would like to fold function arguments which are multiple lines, but leave the single-line function definition as is. For example, the python functions [here](https://github.com/whitead/paper-qa/blob/main/paperqa/qaprompts.py#L4), can be marked and folded in some way (similar to VSCode's behavior). Illustrated below:

<img width="716" alt="Screenshot 2023-04-03 at 09 48 11" src="https://user-images.githubusercontent.com/335719/229393683-4633192d-9f30-43ac-84e0-a4b5611767bf.png">

But without regex support, I don't know how to implement this. I am wondering if there would be a simple and flexible way.

**Comment by jcs090218** [comment]
It should be pretty simple to do. You need to first declare a starting node, probably `argument_list` or something similar, then find the end node to make up the folding range. The end node should be the last node in `argument_list` node. Here is the logic (not the code):

```sh
# Once you defined `argument_list` in `ts-fold-parsers.el`, then ts-fold will find it for you!
# 
# The starting node should be `(` token
starting_node = 'argument_list' node

# Get the last children, this should be `)` token
last_child = get_children(starting_node).last  # or find it with sibling, depends on the AST

# Find the pos
start_pos = node_end_pos(starting_node)  # The node is `(`, start fold after this node
end_pos = node_beg_pos(last_child)       # The node is `)`, end fold before this node

# This is the folding range
range = (start_pos, end_pos)
```

Result should be something similar to:

```csharp
//       V                  V
void Add(int a, int b, int c)

/* | Will fold into
 * |
 * V
 */
void Add(...)
```

For range, see function

https://github.com/emacs-tree-sitter/ts-fold/blob/7a46b695a1fd4336d16c4627bc916446b1f4969a/ts-fold.el#L407-L413

With this method, is likely going to be accurate since it relies on AST and not regex. More importantly, it's fast!

**Comment by tlkahn** [comment]
Thanks a lot! I ended up with what I want using this line:

```elisp
(push '(argument_list . ts-fold-range-seq) (alist-get 'python-mode ts-fold-range-alist))
```

Appreciate the fast help!
