### ISSUE TITLE
Error: (void-function ts-docstr-find-children)

### ISSUE THREAD

**Issue by sbwcwso** [emacs-tree-sitter/ts-fold#59]
The function `ts-docstr-find-children`  is not defined.

https://github.com/emacs-tree-sitter/ts-fold/blob/27c6bc4819029a91174e1106184ba07ef3dec856/ts-fold.el#L624

**Comment by jcs090218** [comment]
Fixed in bc3e5dda46405839197536e06875d469ac992070. I was confused with another TreeSitter package [ts-docstr](https://github.com/emacs-vs/ts-docstr). 😓
