### ISSUE TITLE
Not work in java

### ISSUE THREAD

**Issue by sbwcwso** [emacs-tree-sitter/ts-fold#60]
Works fine at python-mode, but doesn't works at all at java-mode.

```
Minor modes enabled in this buffer: Command-Log Display-Line-Numbers
Evil-Collection-Unimpaired Evil-Local Evil-Matchit Evil-Surround
Evil-Visualstar Font-Lock Lsp-Bridge Tree-Sitter-Hl Tree-Sitter
Ts-Fold-Indicators Ts-Fold Undo-Tree

The major mode is Java//lh mode defined in cc-mode.el:

Major mode for editing Java code.
To submit a problem report, enter ‘M-x c-submit-bug-report’ from a
‘java-mode’ buffer.  This automatically sets up a mail buffer with
version information already added.  You just need to add a description
of the problem, including a reproducible test case, and send the
message.

To see what version of CC Mode you are running, enter ‘M-x c-version’.

The hook ‘c-mode-common-hook’ is run with no args at mode
initialization, then ‘java-mode-hook’.
```

The Java//lh is very strange, I don't konw why it isn't java mode

**Comment by jcs090218** [comment]
It does work in Java. Is there any error? Can you post the steps to reproduce the behavior? 🤔

**Comment by sbwcwso** [comment]
> It does work in Java. Is there any error? Can you post the steps to reproduce the behavior? thinking

Where can I see the error message?
Like the follow code, the fold does not working, and there is no message in the `*Message*`. Is ther anything to do with my java mode, if I need extra settings for java?

```java
class Hello {
    public static void main(String[] args) {
        int number = 10;

        if (number > 0) {
            System.out.println("Number is positive.");
        } else if (number < 0) {
            System.out.println("Number is negative.");
        } else {
            System.out.println("Number is zero.");
        }
    }
}
```

**Comment by jcs090218** [comment]
> Where can I see the error message?

Regularly in the `*Messages*` buffer or at the bottom of your window (echo area).

![2023-06-04-19-17-33](https://github.com/emacs-tree-sitter/ts-fold/assets/8685505/095eb6b5-0d7d-4123-b839-b761f06eb793)

It works on my end.

IDK... It must be something in your configuration. Try `emacs -q` or get rid of some of your config and see what is affecting this package. 😓

**Comment by sbwcwso** [comment]
> > Where can I see the error message?
> 
> Regularly in the `*Messages*` buffer or at the bottom of your window (echo area).
> 
> ![2023-06-04-19-17-33](https://user-images.githubusercontent.com/8685505/243236638-095eb6b5-0d7d-4123-b839-b761f06eb793.gif)
> 
> It works on my end.
> 
> IDK... It must be something in your configuration. Try `emacs -q` or get rid of some of your config and see what is affecting this package. sweat

My bad, when I use emacs -Q, everything works fine. Thank you very much.
