### ISSUE TITLE
Error saying tree-sitter-mode not enabled 

### ISSUE THREAD

**Issue by ezmiller** [emacs-tree-sitter/ts-fold#61]
I am on Emacs 29.1 and have installed tree-sitter libs for txs, typescript. and javascript. When I load a buffer and try to run a `ts-fold` command (e.g. `ts-fold-toggle`) I get an error:

> Ignored, tree-sitter-mode is not enabled in the current buffer

However, if I check to see if I'm running a tree sitter mode by doing `C-:` and evaluating `(symbol-name major-mode)`, I get `typescript-ts-mode`. 

I am not sure what may be going on here. Any guidance would be greatly appreciated.

**Comment by jcs090218** [comment]
I assumed you are using the built-in `treesit.el` (which came with Emacs 29.1). This package only supports the external [tree-sitter.el](https://github.com/emacs-tree-sitter/elisp-tree-sitter), so you will need to install and enable that package. For the built-in treesit.el support, please follow this issue #48.

**Comment by xmawja** [comment]
do you have any plan to support emacs 29.1 built-in treesit.el ?

**Comment by jcs090218** [comment]
Yes, I'll support built-in treesit.el. However, I'm currently busy with other stuff in my life. I'll try to get back on track ASAP!

**Comment by getong** [comment]
9 months later, any progress?
