### ISSUE TITLE
julia language support

### ISSUE THREAD

**Issue by SrAceves** [emacs-tree-sitter/ts-fold#8]
Are there any plans to support [julia](https://github.com/tree-sitter/tree-sitter-julia)? I've coded this  function

``` emacs-lisp
(defun tree-sitter-fold-range-julia (node)
  (let* ((a (tsc-node-end-position (tsc-get-nth-named-child node 0)))
         (b (- (tsc-node-end-position node) 3))) ;; offset by three to include `end'
    (cons a b)))
```
for the [tree-sitter-fold](https://github.com/junyi-hou/tree-sitter-fold) package to fold the `function_definition`, `macro_definition`, `struct_definition` and `module_definition` nodes; it works, but it sometimes fails to load (I don't know why).

Also, the code here looks much more comprehensive (and standardized); I also don't know enough elisp to understand it or contribute with my own julia parser. Since julia uses the `function ... end` syntax, I feel it shouldn't be too different from ruby (maybe?)

Thanks.

**Comment by jcs090218** [comment]
Hi, thanks for the advice! I would love to support as much languages as possible, so my answer is YES, I would love to! ❤️ 

Although I am quite busy recently, I will try to look into it in my spare time! 😅

**Comment by SrAceves** [comment]
Alternatively, If you write a tutorial on how create a parser or describe the package's parser API (be gentle on us lay people) perhaps I can contribute.

**Comment by jcs090218** [comment]
Good idea. I will try to work on the documentation within few days!

**Comment by jcs090218** [comment]
Added the documentation about creating folding and summary parsers in #9. See the updated README in the master branch!
